name: design_system
description: Tasarim tokenlari, tema, yeniden kullanilabilir widget kutuphanesi.
publish_to: none
version: 0.1.0

environment:
  sdk: ^3.12.0

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/
